### PR TITLE
Dockerfile add libboost and repair, add run.sh

### PR DESCRIPTION
**Pull request by bowertree**
Add libboost-all-dev to podman container

Fix some regressions with the Dockerfile I committed -- previous version doesn't complete but because of filesystem state I didn't catch the error the change introduced.

Added run.sh to make it easy to start the container and map the ports.

### CODE REVIEW

**Review by BartMassey — COMMENTED** [review]
Are we sure we want to do the personal Github setup by default in this container? I feel like anyone who wants to do development inside the container kind of knows how to do this already?

I would probably just depend on `libboost-math-dev` for now? It pulls in `libboost-dev` anyhow in spite of "modular" but maybe someday…

**Review by BartMassey — APPROVED** [review]
I'll document this once this is merged.

**Comment by bowertree** [comment]
It defaults to no in the y/n if you just press enter, or I thought it did. It will pull using http with no key. I can make the default N more obvious in the prompt.

For the way I’ve been building and testing this it is quite nice to have the whole process tied in. I’d like to keep the option because it isn’t that for me to delete the repo and re-pull and rebuild just to make sure everything still works. If someone wanted to do it their own way they can always run ‘podman build’ manually.

Agreed on just pulling in libboost-math-dev, or at least gesturing toward just pulling in -math, I’ll revise.

**Review by BartMassey — APPROVED** [review]

**Comment by bowertree** [comment]
@BartMassey was right the prompt for GitHub crews was not the best idea. I moved it to a --github option to the build.sh script

**Pull request merged**
